# TCL File Generated by Component Editor 9.0sp1
# Tue Feb 16 11:55:27 EST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | Nios_LCD_Component "Nios_LCD_Component" v1.0
# | Adam Kinsman, Henry Ko and Nicola Nicolici from McMaster University, Canada 2010.02.16.11:55:27
# | Custom component for the LCD
# | 
# | Z:/test_release/coe4ds4_lab4/experiment1/Nios_LCD_Component/Nios_LCD_Component.sv
# | 
# |    ./Nios_LCD_Component.sv syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module Nios_LCD_Component
# | 
set_module_property DESCRIPTION "Custom component for the LCD"
set_module_property NAME Nios_LCD_Component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP coe4ds4
set_module_property AUTHOR "Adam Kinsman, Henry Ko and Nicola Nicolici from McMaster University, Canada"
set_module_property DISPLAY_NAME Nios_LCD_Component
set_module_property TOP_LEVEL_HDL_FILE Nios_LCD_Component.sv
set_module_property TOP_LEVEL_HDL_MODULE Nios_LCD_Component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Nios_LCD_Component.sv {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_clock
# | 
add_interface global_signals_clock clock end
set_interface_property global_signals_clock ptfSchematicName ""

set_interface_property global_signals_clock ENABLED true

add_interface_port global_signals_clock LCD_Component_clk clk Input 1
add_interface_port global_signals_clock LCD_Component_resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_export
# | 
add_interface global_signals_export conduit start

set_interface_property global_signals_export ASSOCIATED_CLOCK global_signals_clock
set_interface_property global_signals_export ENABLED true

add_interface_port global_signals_export DRAM_DQ export Bidir 16
add_interface_port global_signals_export DRAM_ADDR export Output 12
add_interface_port global_signals_export DRAM_LDQM export Output 1
add_interface_port global_signals_export DRAM_UDQM export Output 1
add_interface_port global_signals_export DRAM_WE_N export Output 1
add_interface_port global_signals_export DRAM_CAS_N export Output 1
add_interface_port global_signals_export DRAM_RAS_N export Output 1
add_interface_port global_signals_export DRAM_CS_N export Output 1
add_interface_port global_signals_export DRAM_BA_0 export Output 1
add_interface_port global_signals_export DRAM_BA_1 export Output 1
add_interface_port global_signals_export DRAM_CLK export Output 1
add_interface_port global_signals_export DRAM_CKE export Output 1
add_interface_port global_signals_export GPIO_0 export Bidir 36
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Image
# | 
add_interface Image avalon end
set_interface_property Image addressAlignment DYNAMIC
set_interface_property Image bridgesToMaster ""
set_interface_property Image burstOnBurstBoundariesOnly false
set_interface_property Image holdTime 0
set_interface_property Image isMemoryDevice true
set_interface_property Image isNonVolatileStorage false
set_interface_property Image linewrapBursts false
set_interface_property Image maximumPendingReadTransactions 0
set_interface_property Image printableDevice false
set_interface_property Image readLatency 0
set_interface_property Image readWaitTime 1
set_interface_property Image setupTime 0
set_interface_property Image timingUnits Cycles
set_interface_property Image writeWaitStates 1
set_interface_property Image writeWaitTime 1

set_interface_property Image ASSOCIATED_CLOCK global_signals_clock
set_interface_property Image ENABLED true

add_interface_port Image Image_address address Input 4
add_interface_port Image Image_chipselect chipselect Input 1
add_interface_port Image Image_read read Input 1
add_interface_port Image Image_write write Input 1
add_interface_port Image Image_readdata readdata Output 32
add_interface_port Image Image_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Touchpanel
# | 
add_interface Touchpanel avalon end
set_interface_property Touchpanel addressAlignment DYNAMIC
set_interface_property Touchpanel bridgesToMaster ""
set_interface_property Touchpanel burstOnBurstBoundariesOnly false
set_interface_property Touchpanel holdTime 0
set_interface_property Touchpanel isMemoryDevice true
set_interface_property Touchpanel isNonVolatileStorage false
set_interface_property Touchpanel linewrapBursts false
set_interface_property Touchpanel maximumPendingReadTransactions 0
set_interface_property Touchpanel printableDevice false
set_interface_property Touchpanel readLatency 0
set_interface_property Touchpanel readWaitTime 1
set_interface_property Touchpanel setupTime 0
set_interface_property Touchpanel timingUnits Cycles
set_interface_property Touchpanel writeWaitStates 1
set_interface_property Touchpanel writeWaitTime 1

set_interface_property Touchpanel ASSOCIATED_CLOCK global_signals_clock
set_interface_property Touchpanel ENABLED true

add_interface_port Touchpanel Touchpanel_address address Input 4
add_interface_port Touchpanel Touchpanel_chipselect chipselect Input 1
add_interface_port Touchpanel Touchpanel_read read Input 1
add_interface_port Touchpanel Touchpanel_write write Input 1
add_interface_port Touchpanel Touchpanel_readdata readdata Output 32
add_interface_port Touchpanel Touchpanel_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Touchpanel_irq
# | 
add_interface Touchpanel_irq interrupt end
set_interface_property Touchpanel_irq associatedAddressablePoint Touchpanel

set_interface_property Touchpanel_irq ASSOCIATED_CLOCK global_signals_clock
set_interface_property Touchpanel_irq ENABLED true

add_interface_port Touchpanel_irq Touchpanel_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Console
# | 
add_interface Console avalon end
set_interface_property Console addressAlignment DYNAMIC
set_interface_property Console bridgesToMaster ""
set_interface_property Console burstOnBurstBoundariesOnly false
set_interface_property Console holdTime 0
set_interface_property Console isMemoryDevice true
set_interface_property Console isNonVolatileStorage false
set_interface_property Console linewrapBursts false
set_interface_property Console maximumPendingReadTransactions 0
set_interface_property Console printableDevice false
set_interface_property Console readLatency 0
set_interface_property Console readWaitTime 1
set_interface_property Console setupTime 0
set_interface_property Console timingUnits Cycles
set_interface_property Console writeWaitStates 1
set_interface_property Console writeWaitTime 1

set_interface_property Console ASSOCIATED_CLOCK global_signals_clock
set_interface_property Console ENABLED true

add_interface_port Console Console_address address Input 11
add_interface_port Console Console_chipselect chipselect Input 1
add_interface_port Console Console_read read Input 1
add_interface_port Console Console_write write Input 1
add_interface_port Console Console_readdata readdata Output 32
add_interface_port Console Console_writedata writedata Input 32
# | 
# +-----------------------------------
