# TCL File Generated by Component Editor 9.0sp1
# Fri Jan 29 18:47:51 EST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | Nios_LCD_Camera_Component "Nios_LCD_Camera_Component" v1.0
# | Adam Kinsman, Henry Ko and Nicola Nicolici from McMaster University, Canada 2010.01.29.18:47:51
# | 
# | 
# | C:/Courses/coe4ds4/2010/Test_release/coe4ds4_lab4/experiment3/Nios_LCD_Camera_Component/Nios_LCD_Camera_Component.sv
# | 
# |    ./Nios_LCD_Camera_Component.sv syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module Nios_LCD_Camera_Component
# | 
set_module_property DESCRIPTION ""
set_module_property NAME Nios_LCD_Camera_Component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP coe4ds4
set_module_property AUTHOR "Adam Kinsman, Henry Ko and Nicola Nicolici from McMaster University, Canada"
set_module_property DISPLAY_NAME Nios_LCD_Camera_Component
set_module_property TOP_LEVEL_HDL_FILE Nios_LCD_Camera_Component.sv
set_module_property TOP_LEVEL_HDL_MODULE Nios_LCD_Camera_Component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Nios_LCD_Camera_Component.sv {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_clock
# | 
add_interface global_signals_clock clock end
set_interface_property global_signals_clock ptfSchematicName ""

set_interface_property global_signals_clock ENABLED true

add_interface_port global_signals_clock LCD_Camera_Component_clk clk Input 1
add_interface_port global_signals_clock LCD_Camera_Component_resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_export
# | 
add_interface global_signals_export conduit start

set_interface_property global_signals_export ASSOCIATED_CLOCK global_signals_clock
set_interface_property global_signals_export ENABLED true

add_interface_port global_signals_export DRAM_DQ export Bidir 16
add_interface_port global_signals_export DRAM_ADDR export Output 12
add_interface_port global_signals_export DRAM_LDQM export Output 1
add_interface_port global_signals_export DRAM_UDQM export Output 1
add_interface_port global_signals_export DRAM_WE_N export Output 1
add_interface_port global_signals_export DRAM_CAS_N export Output 1
add_interface_port global_signals_export DRAM_RAS_N export Output 1
add_interface_port global_signals_export DRAM_CS_N export Output 1
add_interface_port global_signals_export DRAM_BA_0 export Output 1
add_interface_port global_signals_export DRAM_BA_1 export Output 1
add_interface_port global_signals_export DRAM_CLK export Output 1
add_interface_port global_signals_export DRAM_CKE export Output 1
add_interface_port global_signals_export GPIO_0 export Bidir 36
add_interface_port global_signals_export GPIO_1 export Bidir 36
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Touchpanel
# | 
add_interface Touchpanel avalon end
set_interface_property Touchpanel addressAlignment DYNAMIC
set_interface_property Touchpanel bridgesToMaster ""
set_interface_property Touchpanel burstOnBurstBoundariesOnly false
set_interface_property Touchpanel holdTime 0
set_interface_property Touchpanel isMemoryDevice true
set_interface_property Touchpanel isNonVolatileStorage false
set_interface_property Touchpanel linewrapBursts false
set_interface_property Touchpanel maximumPendingReadTransactions 0
set_interface_property Touchpanel printableDevice false
set_interface_property Touchpanel readLatency 0
set_interface_property Touchpanel readWaitTime 1
set_interface_property Touchpanel setupTime 0
set_interface_property Touchpanel timingUnits Cycles
set_interface_property Touchpanel writeWaitStates 1
set_interface_property Touchpanel writeWaitTime 1

set_interface_property Touchpanel ASSOCIATED_CLOCK global_signals_clock
set_interface_property Touchpanel ENABLED true

add_interface_port Touchpanel Touchpanel_address address Input 4
add_interface_port Touchpanel Touchpanel_chipselect chipselect Input 1
add_interface_port Touchpanel Touchpanel_read read Input 1
add_interface_port Touchpanel Touchpanel_write write Input 1
add_interface_port Touchpanel Touchpanel_readdata readdata Output 32
add_interface_port Touchpanel Touchpanel_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Touchpanel_irq
# | 
add_interface Touchpanel_irq interrupt end
set_interface_property Touchpanel_irq associatedAddressablePoint Touchpanel

set_interface_property Touchpanel_irq ASSOCIATED_CLOCK global_signals_clock
set_interface_property Touchpanel_irq ENABLED true

add_interface_port Touchpanel_irq Touchpanel_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Camera
# | 
add_interface Camera avalon end
set_interface_property Camera addressAlignment DYNAMIC
set_interface_property Camera bridgesToMaster ""
set_interface_property Camera burstOnBurstBoundariesOnly false
set_interface_property Camera holdTime 0
set_interface_property Camera isMemoryDevice true
set_interface_property Camera isNonVolatileStorage false
set_interface_property Camera linewrapBursts false
set_interface_property Camera maximumPendingReadTransactions 0
set_interface_property Camera printableDevice false
set_interface_property Camera readLatency 0
set_interface_property Camera readWaitTime 1
set_interface_property Camera setupTime 0
set_interface_property Camera timingUnits Cycles
set_interface_property Camera writeWaitStates 1
set_interface_property Camera writeWaitTime 1

set_interface_property Camera ASSOCIATED_CLOCK global_signals_clock
set_interface_property Camera ENABLED true

add_interface_port Camera Camera_address address Input 4
add_interface_port Camera Camera_chipselect chipselect Input 1
add_interface_port Camera Camera_read read Input 1
add_interface_port Camera Camera_write write Input 1
add_interface_port Camera Camera_readdata readdata Output 32
add_interface_port Camera Camera_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Console
# | 
add_interface Console avalon end
set_interface_property Console addressAlignment DYNAMIC
set_interface_property Console bridgesToMaster ""
set_interface_property Console burstOnBurstBoundariesOnly false
set_interface_property Console holdTime 0
set_interface_property Console isMemoryDevice true
set_interface_property Console isNonVolatileStorage false
set_interface_property Console linewrapBursts false
set_interface_property Console maximumPendingReadTransactions 0
set_interface_property Console printableDevice false
set_interface_property Console readLatency 0
set_interface_property Console readWaitTime 1
set_interface_property Console setupTime 0
set_interface_property Console timingUnits Cycles
set_interface_property Console writeWaitStates 1
set_interface_property Console writeWaitTime 1

set_interface_property Console ASSOCIATED_CLOCK global_signals_clock
set_interface_property Console ENABLED true

add_interface_port Console Console_address address Input 11
add_interface_port Console Console_chipselect chipselect Input 1
add_interface_port Console Console_read read Input 1
add_interface_port Console Console_write write Input 1
add_interface_port Console Console_readdata readdata Output 32
add_interface_port Console Console_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Imageline
# | 
add_interface Imageline avalon end
set_interface_property Imageline addressAlignment DYNAMIC
set_interface_property Imageline bridgesToMaster ""
set_interface_property Imageline burstOnBurstBoundariesOnly false
set_interface_property Imageline holdTime 0
set_interface_property Imageline isMemoryDevice true
set_interface_property Imageline isNonVolatileStorage false
set_interface_property Imageline linewrapBursts false
set_interface_property Imageline maximumPendingReadTransactions 0
set_interface_property Imageline printableDevice false
set_interface_property Imageline readLatency 0
set_interface_property Imageline readWaitTime 1
set_interface_property Imageline setupTime 0
set_interface_property Imageline timingUnits Cycles
set_interface_property Imageline writeWaitStates 1
set_interface_property Imageline writeWaitTime 1

set_interface_property Imageline ASSOCIATED_CLOCK global_signals_clock
set_interface_property Imageline ENABLED true

add_interface_port Imageline Imageline_address address Input 11
add_interface_port Imageline Imageline_chipselect chipselect Input 1
add_interface_port Imageline Imageline_read read Input 1
add_interface_port Imageline Imageline_write write Input 1
add_interface_port Imageline Imageline_readdata readdata Output 32
add_interface_port Imageline Imageline_writedata writedata Input 32
add_interface_port Imageline Imageline_waitrequest waitrequest Output 1
# | 
# +-----------------------------------
