# TCL File Generated by Component Editor 9.0sp1
# Sun Feb 28 20:03:11 EST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SEG7_Display "SEG7_Display" v1.0
# | null 2010.02.28.20:03:11
# | 
# | 
# | C:/Courses/coe4ds4/2010/Test_release/coe4ds4_lab6/experiment1/altera_up_avalon_seg7/SEG7_Display.v
# | 
# |    ./SEG7_Display.v syn
# |    ./SEG7_LUT_8.v syn
# |    ./SEG7_LUT.v syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module SEG7_Display
# | 
set_module_property DESCRIPTION ""
set_module_property NAME SEG7_Display
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP coe4ds4_components
set_module_property DISPLAY_NAME SEG7_Display
set_module_property TOP_LEVEL_HDL_FILE SEG7_Display.v
set_module_property TOP_LEVEL_HDL_MODULE SEG7_Display
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SEG7_Display.v SYNTHESIS
add_file SEG7_LUT_8.v SYNTHESIS
add_file SEG7_LUT.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point seg7_display_clock
# | 
add_interface seg7_display_clock clock end
set_interface_property seg7_display_clock ptfSchematicName ""

set_interface_property seg7_display_clock ENABLED true

add_interface_port seg7_display_clock iCLK clk Input 1
add_interface_port seg7_display_clock iRST_N reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point seg7_display
# | 
add_interface seg7_display avalon end
set_interface_property seg7_display addressAlignment DYNAMIC
set_interface_property seg7_display bridgesToMaster ""
set_interface_property seg7_display burstOnBurstBoundariesOnly false
set_interface_property seg7_display holdTime 0
set_interface_property seg7_display isMemoryDevice false
set_interface_property seg7_display isNonVolatileStorage false
set_interface_property seg7_display linewrapBursts false
set_interface_property seg7_display maximumPendingReadTransactions 0
set_interface_property seg7_display printableDevice false
set_interface_property seg7_display readLatency 0
set_interface_property seg7_display readWaitTime 1
set_interface_property seg7_display setupTime 0
set_interface_property seg7_display timingUnits Cycles
set_interface_property seg7_display writeWaitStates 1
set_interface_property seg7_display writeWaitTime 1

set_interface_property seg7_display ASSOCIATED_CLOCK seg7_display_clock
set_interface_property seg7_display ENABLED true

add_interface_port seg7_display iDIG writedata Input 32
add_interface_port seg7_display iWR write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point seg7_display_export
# | 
add_interface seg7_display_export conduit start

set_interface_property seg7_display_export ASSOCIATED_CLOCK seg7_display_clock
set_interface_property seg7_display_export ENABLED true

add_interface_port seg7_display_export oSEG0 export Output 7
add_interface_port seg7_display_export oSEG1 export Output 7
add_interface_port seg7_display_export oSEG2 export Output 7
add_interface_port seg7_display_export oSEG3 export Output 7
add_interface_port seg7_display_export oSEG4 export Output 7
add_interface_port seg7_display_export oSEG5 export Output 7
add_interface_port seg7_display_export oSEG6 export Output 7
add_interface_port seg7_display_export oSEG7 export Output 7
# | 
# +-----------------------------------
